# -*- coding: utf-8 -*-
"""鞋服 SPU 表：圈定款式，复现断码 / 缺码 / 缺货预警。"""

from .formula import (
    BAIHUO_REPLENISH_COVER_DAYS,
    REPLENISH_COVER_DAYS,
    SKIP_WARNING_TAGS,
    TURNOVER_ALERT_DAYS,
    daily_avg,
    daily_avg_baihuo,
    monthly_sales_baihuo,
    baihuo_window_rates,
    obsolete_label,
    order_qty,
    replenish_qty,
    sku_code_status,
    style_stock,
    style_warning,
    style_year,
)
from .roster import (
    BAIHUO_LABEL,
    CATEGORY_LINES,
    parse_product_attrs,
    product_in_baihuo_scope,
    product_in_scope,
    skip_stockout_warning,
)
from .service import (
    BAIHUO_SNAPSHOT_TABLE,
    BOARD_APPAREL,
    BOARD_BAIHUO,
    BOARDS,
    SNAPSHOT_TABLE,
    SPU_PLAN_TABLES,
    DataMissing,
    build_style_alerts,
    format_alert_text,
    load_products,
    load_style_snapshot,
    normalize_board,
    save_style_snapshot,
    scoped_style_ids,
    snapshot_table,
)
from .workbook import (
    TOTAL_COLUMNS,
    style_workbook_path,
    write_style_workbook,
)

__all__ = [
    "BAIHUO_LABEL",
    "BAIHUO_SNAPSHOT_TABLE",
    "BOARD_APPAREL",
    "BOARD_BAIHUO",
    "BOARDS",
    "CATEGORY_LINES",
    "DataMissing",
    "BAIHUO_REPLENISH_COVER_DAYS",
    "REPLENISH_COVER_DAYS",
    "SKIP_WARNING_TAGS",
    "SNAPSHOT_TABLE",
    "SPU_PLAN_TABLES",
    "TOTAL_COLUMNS",
    "TURNOVER_ALERT_DAYS",
    "build_style_alerts",
    "format_alert_text",
    "baihuo_window_rates",
    "daily_avg",
    "daily_avg_baihuo",
    "monthly_sales_baihuo",
    "load_products",
    "load_style_snapshot",
    "normalize_board",
    "obsolete_label",
    "order_qty",
    "parse_product_attrs",
    "product_in_baihuo_scope",
    "product_in_scope",
    "replenish_qty",
    "save_style_snapshot",
    "snapshot_table",
    "scoped_style_ids",
    "sku_code_status",
    "skip_stockout_warning",
    "style_stock",
    "style_warning",
    "style_workbook_path",
    "style_year",
    "write_style_workbook",
]
